fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    apt: "git://github.com/puppetlabs/puppetlabs-apt.git"
    inifile: "git://github.com/puppetlabs/puppetlabs-inifile.git"
    wget: "git://github.com/maestrodev/puppet-wget.git"
  symlinks:
    hhvm: "#{source_dir}"

